### ISSUE TITLE
since_id

### ISSUE THREAD

**Issue by nisehime** [igorbrigadir/twitter-advanced-search#10]
`min_id` doesn't seem to work at all. Instead use `since_id`. It works together with `max_id` as well.

**Comment by pushshift** [comment]
From recollection, Twitter always sorts responses in descending order. AFAIK, min_id (or since_id) are basically useless since you can implement that client side and just stop once you reach whatever min id you want to set as a boundary.

**Comment by nisehime** [comment]
@pushshift well, it's not about that. Just to make a list more complete a I suggest to add this operator.

**Comment by igorbrigadir** [comment]
Thanks!

You're right - `min_id` always fails, and both `since_id` and `max_id` seem to work together with something else like `from:`, changed `min_id` to `since_id` to fix it.
