### ISSUE TITLE
How can I search for Tweets that have their replies turned off?

### ISSUE THREAD

**Issue by lucahammer** [igorbrigadir/twitter-advanced-search#16]
Twitter started testing this feature on 2020-05-20: https://twitter.com/Twitter/status/1263145271946551300

"from:luca -min_replies:1" would be a workaround, but I would still have to test each Tweet if someone could send a reply.

**Comment by igorbrigadir** [comment]
Gonna reopen this if there's a way to do it, but seems like there's not.
