### ISSUE TITLE
Request: A way to search for audio voice messages

### ISSUE THREAD

**Issue by lucahammer** [igorbrigadir/twitter-advanced-search#17]
From my understanding they are implemented as videos, but maybe there is a way to search for them.

My first idea: "filter:audio", doesn't work.

**Comment by pushshift** [comment]
Have you found one in the wild yet? If so -- id?

**Comment by tibor** [comment]
Didn’t find one yet, but more suggestions:
https://twitter.com/JBabichJapan/status/1273537399172157440
https://twitter.com/MKoletsis/status/1273803543250497536

I guess they wouldn’t use voice as that's too precise. Sometimes they use two word combinations, so maybe filter:video_audio or filter:native_audio could work?

Also it would be possible, that twitter is using a separate card type for Audio.

However, at the moment, none of these seem to work.

**Comment by pushshift** [comment]
I don't have an Apple device so I can't make an audio tweet but I've asked if someone else who does own one can make an audio tweet so we can look into the JSON response and see how they label it internally.

**Comment by pushshift** [comment]
https://twitter.com/IgorBrigadir/status/1275010573583949825?s=20

It looks like currently there is no additional filter for audio tweets. They are basically videos with the user's icon in them and their voice / music / whatever as the audio track.
