### ISSUE TITLE
Code for languages, based on ISO 639-1

### ISSUE THREAD

**Issue by secou** [igorbrigadir/twitter-advanced-search#19]
Hi (and thanks for the list). Could be interesting to precise that the lang: syntax is based on ISO 639-1 codes. 
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

Sometimes... the detection is poor (for example co, eu, br...)

**Comment by igorbrigadir** [comment]
Yep - i might add a note and link to https://blog.twitter.com/engineering/en_us/a/2015/evaluating-language-identification-performance.html - that discusses accuracy a bit too.

**Comment by igorbrigadir** [comment]
Added, thanks!
