### ISSUE TITLE
Quotation marks around a single word to avoid autocorrection

### ISSUE THREAD

**Issue by secou** [igorbrigadir/twitter-advanced-search#20]
Sometimes it's useful to use quotation marks around a single word to avoid autocorrection. 

For example, with 

seorch from:crid

you will get some tweets with "search" in it...

 and not "seorch"

"seorch" from:crid

will only gives you good responses. 

![Cj3zGQkWkAAYrDu](https://user-images.githubusercontent.com/4340007/89775934-2333b000-db09-11ea-879e-a74238e5bff9.jpg)

**Comment by igorbrigadir** [comment]
Added a note, thanks!
