### ISSUE TITLE
Known bug: Twitters search operator for lists, Tweetdecks List-Search doesn’t work anymore

### ISSUE THREAD

**Issue by tibor** [igorbrigadir/twitter-advanced-search#22]
If someone is struggling to use twitters `list:` search operator or tweetdecks built in functionality to search for keywords inside a list, twitter is aware of the problem and will fix it:
https://twitter.com/pavtalk/status/1305317270462361602

**Comment by shijithpk** [comment]
Yeah, `list:user/list-slug` wasn't working for a few days, it's started working again for me atleast

**Comment by igorbrigadir** [comment]
Thanks for the update!
