### ISSUE TITLE
Two more operators

### ISSUE THREAD

**Issue by secou** [igorbrigadir/twitter-advanced-search#25]
Hi Igor, 
thanks to the "share" feature of TweetDeck (at the end of any column), I found two operators I never noticed
until_time:
since_time:
folllowed by an epoch timestamp in seconds
So until_time:1569483022 : is related to september 26 2019 - 07:30:22

**Comment by igorbrigadir** [comment]
Oh awesome! Thanks so much! I'll add those in!

**Comment by igorbrigadir** [comment]
added!
