### ISSUE TITLE
Twitter New labels for government and state-affiliated media accounts

### ISSUE THREAD

**Issue by putuoka** [igorbrigadir/twitter-advanced-search#28]
For example https://twitter.com/XHNews/status/1370493013407899648

How to find tweet only from state-affiliated media label?

**Comment by igorbrigadir** [comment]
Yeah i'd like to be able to search for those but i don't think there's a way to find all those users apart from whatever lists twitter put out https://help.twitter.com/en/rules-and-policies/state-affiliated

You may have to create your own twitter list, and use the `list:` operator instead.

**Comment by Mstandastote** [comment]
#28###

**Comment by igorbrigadir** [comment]
There's no sign that these are going to be in the web search, but the labels will be in the API soon I think: 
https://twittercommunity.com/t/share-your-input-on-adding-tweet-profile-labels-to-the-twitter-api-v2/167678

Will revisit this after that's implemented!
