### ISSUE TITLE
Filter by users who likes/ retweet a specific post

### ISSUE THREAD

**Issue by sufyanhamid** [igorbrigadir/twitter-advanced-search#32]
Hi @igorbrigadir !!
First of all thanks for this concise material, it helps me a lot to know about the advanced twitter search mechanism.
Secondly I have a question regarding search query. Is there a way to get the list of users who like/ Retweet my specific post ? Hopefully you will understand my query and help me to do this in a right way.

Thanks in advance :)

**Comment by igorbrigadir** [comment]
> Filter by users who likes/ retweet a specific post

There is no way to do this that i know of.

> Is there a way to get the list of users who like/ Retweet my specific post ?

Technically yes but not via advanced web search. You have to use the API.

For listing likes there's a v2 endpoint (in v1.1 there's no equivalent): https://developer.twitter.com/en/docs/twitter-api/tweets/likes/api-reference/get-tweets-id-liking_users

For listing retweets: there's a v1.1 endpoint (in v2 there's no equivalent): https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/get-statuses-retweeters-ids

Both only return the latest 100 results.

**Comment by sufyanhamid** [comment]
@igorbrigadir thanks for responding. Your response is pretty useful for me.. I have a idea to do this with the help of selenium but it requires login details and once we scrape the data from twitter by logging a profile so I think so twitter will block that account soon if we get huge amount of data ultimately.

**Comment by tibor** [comment]
Why would you want to use selenium? Just use the regular API, it will work well.
