### ISSUE TITLE
Keyword Search for Twitter Lists

### ISSUE THREAD

**Issue by EladRatson** [igorbrigadir/twitter-advanced-search#35]
Hello Igor and thank you for your exceptional work on the Twitter search operators.

I'd like to ask you if you know of a viable way to search Twitter for lists based on keywords in the list title or description?

Thanks.

**Comment by igorbrigadir** [comment]
Unfortunately no - i remember this feature was around years ago, but it no longer works. 

The next best trick i use is searching for tweets with `url:twitter.com/i/lists` like https://twitter.com/search?q=url%3Atwitter.com%2Fi%2Flists%20web3&src=typed_query&f=live that generally works ok

**Comment by tibor** [comment]
I recommend using google for that purpose with `site:twitter.com/*/lists` and if you want to limit the search to the list title, `intitle:keyword`
