### ISSUE TITLE
Seem Like As per june 2022 Advance search query doesn't work anymore after elon musk bought twitter

### ISSUE THREAD

**Issue by putuoka** [igorbrigadir/twitter-advanced-search#36]
example: https://twitter.com/dprhiburanmalam/status/1531957226851553285

when type on search box this query working: ``` Martin garrix ketar ketir ```

but 

with this query isn't working:  ``` Martin garrix ketar ketir filter:videos ``` or ``` Martin garrix ketar ketir filter:media ```

**Comment by lucahammer** [comment]
Musk didn't buy Twitter. The deal isn't through yet.

This looks more like a bug or anti-spam measures. If you find more examples, where filter queries don't work, please share them.

**Comment by putuoka** [comment]
> Musk didn't buy Twitter. The deal isn't through yet.
> 
> This looks more like a bug or anti-spam measures. If you find more examples, where filter queries don't work, please share them.

i don't think this bugs because not only 1 tweet but massive. for example this query:

``` filter:videos min_replies:20 min_faves:300 lang:en ```

before musk buy twitter the query results is much much more now it's few

**Comment by lucahammer** [comment]
I get many results with that query. 
![image](https://user-images.githubusercontent.com/1390793/171595775-bb9def17-b6c1-48cf-bd0a-aa6a91d86261.png)

**Comment by putuoka** [comment]
i mean, before u can get many tweet below 1 minutes. now it has hours. that's indicated many video not captured in the results

**Comment by igorbrigadir** [comment]
Yeah, unfortunately the web search is flaky sometimes, it's not unusual to have no results come up for a query that definitely has results - sometimes there's a cache missing or something times out etc.

Sometimes what works is restricting the time range, or even altering the query by rearranging the keywords sometimes makes it work. 

The only examples where twitter has intervened into search results that i've noticed was with COVID results and suicide (they show an extra banner), and mass shootings / terror acts to remove graphic results.

Feel free to add more examples here in the issue for future - closed issues still work for comments.
