### ISSUE TITLE
only retrieves a few tweets

### ISSUE THREAD

**Issue by aptitude-learn** [igorbrigadir/twitter-advanced-search#48]
I was able to retrieve many tweets dated all the way back to 2015 a few days ago, but now I can only retrieve tweets from the past month. The only difference between the queries is that, a few days ago I was retrieving based on _user,_ and now I am attempting based on _tweet content_. I checked Twitter, there's definitely more tweets that should be retrieved that the scraper is not retrieving,

**Comment by igorbrigadir** [comment]
Yeah - unfortunately, there's not much you can do - the search index is sometimes updated, sometimes times out - so best strategy is to maybe try again, or add or remove some operators - like, if a search is failing, try adding a `lang:en` in there to make it more restrictive if possible - or remove an operator.
