### ISSUE TITLE
Twitter is messing with filter:xxx right now

### ISSUE THREAD

**Issue by fireattack** [igorbrigadir/twitter-advanced-search#49]
It has been like this for days so I guess I will make a post. I don't think we should update the list yet, but it's worth a mention IMO.

Currently, some of the filters straight up do not work. 

E.g. `filter:follows` -- it shows "Something went wrong. Try reloading." in Latest and shows nothing in Top.

Some don't work as intended in Latest (`&f=live`) tab.

* `filter:images` now only shows tweets with external image hosting website (such as Flickr, or good ol' twitpic) URLs. It works fine in Top tab. `filter:twimg` still works fine.
* `filter:media` and `filter:native_video` also don't work in Latest. they show nothing. They all work fine in Top. 
* Surprisingly, `filter:videos` still works. 

I'm too lazy to go over all of them, so here you go.

**Comment by igorbrigadir** [comment]
Thanks! It's worth keeping this issue open here for reference!

**Comment by harrypython** [comment]
I have the same problem in twitter webpage but in tweetdeck still working fine.

**Comment by fireattack** [comment]
filter:images, filter:media, filter:native_video now are working again in Latest tab. 

`filter:follows` is still broken, but I don't use it frequently enough to know if that's a recent thing.

**Comment by fireattack** [comment]
`filter:follows` works now too.

Closing the ticket.
