### ISSUE TITLE
user_id is not the same as user

### ISSUE THREAD

**Issue by Mike-Honey** [igorbrigadir/twitter-advanced-search#50]
This is a great resource - thank you for compiling it.

I did stumble using the **quoted_user_id:user_id** entry. Eventually, I figured out that **user_id** is not the same as **user**. 

I found this tool that can translate between the two - not sure if there are other/better methods?
https://tweeterid.com/

Perhaps you could explain that in the doc?

**Comment by igorbrigadir** [comment]
Thanks! Yes - Added!
