### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by igorbrigadir** [igorbrigadir/twitter-advanced-search#6]
Add more examples of queries

**Comment by pushshift** [comment]
I think this is worth noting -- You can use min_id / max_id as time delimiters:

Here's the code to convert a Twitter ID to microsecond epoch:

(tweet_id >> 22) + 1288834974657 -- This gives the millisecond epoch of when the tweet was created.

Convert from epoch back to a tweet id:

(millisecond_epoch - 1288834974657) << 22 = tweet id (This works for all tweets after Snowflake was implemented)

**Here's a use case:**

You want to start gathering all tweets for specific search terms starting at a specific time. Let's say this time in August 4, 2019 09:00:00 UTC. You can use the max_id parameter by first converting the millisecond epoch time to a tweet id.

1) August 4, 2019 09:00:00 UTC = 1564909200000 (epoch milliseconds)
2) (1564909200000 - 1288834974657) << 22 = 1157939227653046272 (tweet id)

So if you set max_id to 1157939227653046272, you will start collecting tweets earlier than that datetime. This can be extremely helpful when you need to get a very specific portion of the timeline.

Here's a quick Python function:

```
def convert_milliepoch_to_tweet_id(milliepoch):
    if milliepoch <= 1288834974657:
        raise ValueError("Date is too early (before snowflake implementation)")
    return (milliepoch - 1288834974657) << 22
```

**Comment by pushshift** [comment]
Doh -- I think you already had that. :)

**Comment by igorbrigadir** [comment]
Yep - from you earlier, but the longer description should definitely be there too - i'll add it to the doc at the end if that's ok!

**Comment by pushshift** [comment]
Perfect!
