### ISSUE TITLE
Twitter will soon end support for most geolocation data within Tweets

### ISSUE THREAD

**Issue by pushshift** [igorbrigadir/twitter-advanced-search#8]
It may be helpful to note that Twitter will soon be deprecating geolocational data for tweets (except for tweets with media / pictures).

This article touches on some of the details: 

https://www.theverge.com/2019/6/19/18691174/twitter-location-tagging-geotagging-discontinued-removal

"Twitter removes support for precise geotagging because no one uses it (But it will remain available for photographs)"

**Comment by igorbrigadir** [comment]
Added Geo note on this
