### ISSUE TITLE
More details on Twitter's Snowflake Implementation

### ISSUE THREAD

**Issue by pushshift** [igorbrigadir/twitter-advanced-search#9]
I wrote a preliminary paper on strategies to reconstruct portions of the timeline up to firehose level here: https://docs.google.com/document/d/1xVrPoNutyqTdQ04DXBEZW4ZW4A5RAQW2he7qIpTmG-M/edit

It may also be helpful to include a link to this paper as it also goes into depth about how Twitter's Snowflake implementation works.

**Comment by igorbrigadir** [comment]
Added link to snowflake notes! Thanks!
